### ISSUE TITLE
Not compatible with point lights

### ISSUE THREAD

**Issue by eobet** [BrokenVector/LowPolyShaders#1]
These shaders are only flat shaded for a single directional light.

If you add a point light, the polygons become smooth shaded internally (though still with sharp edges).

Also, if you have a model with smooth polygons, switching to this shader does not turn them flat.

I'm actually unsure of what they do at all, except remove the glossy highlight.

**Comment by michidk** [comment]
Hey @eobet,

A shader can't change the mesh to change it from smooth to flat. As the readme states, this shader ist faster then the standard shader for low poly models (and we never said it renders an mesh flat).


Kind regards,
Michi
